angular.module( 'gj.Geo' ).service( 'Geo', function( gettextCatalog )
{
	var _countries = null;
	var _regions = {};

	this.getCountries = function()
	{
		if ( !_countries ) {
			_countries = [
				{ code: 'AF', name: gettextCatalog.getString( 'Afghanistan' ) },
				{ code: 'AX', name: gettextCatalog.getString( 'Aland Islands' ) },
				{ code: 'AL', name: gettextCatalog.getString( 'Albania' ) },
				{ code: 'DZ', name: gettextCatalog.getString( 'Algeria' ) },
				{ code: 'AS', name: gettextCatalog.getString( 'American Samoa' ) },
				{ code: 'AD', name: gettextCatalog.getString( 'Andorra' ) },
				{ code: 'AO', name: gettextCatalog.getString( 'Angola' ) },
				{ code: 'AI', name: gettextCatalog.getString( 'Anguilla' ) },
				{ code: 'AQ', name: gettextCatalog.getString( 'Antarctica' ) },
				{ code: 'AG', name: gettextCatalog.getString( 'Antigua and Barbuda' ) },
				{ code: 'AR', name: gettextCatalog.getString( 'Argentina' ) },
				{ code: 'AM', name: gettextCatalog.getString( 'Armenia' ) },
				{ code: 'AW', name: gettextCatalog.getString( 'Aruba' ) },
				{ code: 'AU', name: gettextCatalog.getString( 'Australia' ) },
				{ code: 'AT', name: gettextCatalog.getString( 'Austria' ) },
				{ code: 'AZ', name: gettextCatalog.getString( 'Azerbaijan' ) },
				{ code: 'BS', name: gettextCatalog.getString( 'Bahamas' ) },
				{ code: 'BH', name: gettextCatalog.getString( 'Bahrain' ) },
				{ code: 'BD', name: gettextCatalog.getString( 'Bangladesh' ) },
				{ code: 'BB', name: gettextCatalog.getString( 'Barbados' ) },
				{ code: 'BY', name: gettextCatalog.getString( 'Belarus' ) },
				{ code: 'BE', name: gettextCatalog.getString( 'Belgium' ) },
				{ code: 'BZ', name: gettextCatalog.getString( 'Belize' ) },
				{ code: 'BJ', name: gettextCatalog.getString( 'Benin' ) },
				{ code: 'BM', name: gettextCatalog.getString( 'Bermuda' ) },
				{ code: 'BT', name: gettextCatalog.getString( 'Bhutan' ) },
				{ code: 'BO', name: gettextCatalog.getString( 'Bolivia' ) },
				{ code: 'BQ', name: gettextCatalog.getString( 'Bonaire, Saint Eustatius and Saba' ) },
				{ code: 'BA', name: gettextCatalog.getString( 'Bosnia and Herzegovina' ) },
				{ code: 'BW', name: gettextCatalog.getString( 'Botswana' ) },
				{ code: 'BV', name: gettextCatalog.getString( 'Bouvet Island' ) },
				{ code: 'BR', name: gettextCatalog.getString( 'Brazil' ) },
				{ code: 'IO', name: gettextCatalog.getString( 'British Indian Ocean Territory' ) },
				{ code: 'VG', name: gettextCatalog.getString( 'British Virgin Islands' ) },
				{ code: 'BN', name: gettextCatalog.getString( 'Brunei' ) },
				{ code: 'BG', name: gettextCatalog.getString( 'Bulgaria' ) },
				{ code: 'BF', name: gettextCatalog.getString( 'Burkina Faso' ) },
				{ code: 'BI', name: gettextCatalog.getString( 'Burundi' ) },
				{ code: 'KH', name: gettextCatalog.getString( 'Cambodia' ) },
				{ code: 'CM', name: gettextCatalog.getString( 'Cameroon' ) },
				{ code: 'CA', name: gettextCatalog.getString( 'Canada' ) },
				{ code: 'CV', name: gettextCatalog.getString( 'Cape Verde' ) },
				{ code: 'KY', name: gettextCatalog.getString( 'Cayman Islands' ) },
				{ code: 'CF', name: gettextCatalog.getString( 'Central African Republic' ) },
				{ code: 'TD', name: gettextCatalog.getString( 'Chad' ) },
				{ code: 'CL', name: gettextCatalog.getString( 'Chile' ) },
				{ code: 'CN', name: gettextCatalog.getString( 'China' ) },
				{ code: 'CX', name: gettextCatalog.getString( 'Christmas Island' ) },
				{ code: 'CC', name: gettextCatalog.getString( 'Cocos Islands' ) },
				{ code: 'CO', name: gettextCatalog.getString( 'Colombia' ) },
				{ code: 'KM', name: gettextCatalog.getString( 'Comoros' ) },
				{ code: 'CK', name: gettextCatalog.getString( 'Cook Islands' ) },
				{ code: 'CR', name: gettextCatalog.getString( 'Costa Rica' ) },
				{ code: 'HR', name: gettextCatalog.getString( 'Croatia' ) },
				{ code: 'CU', name: gettextCatalog.getString( 'Cuba' ) },
				{ code: 'CW', name: gettextCatalog.getString( 'Curacao' ) },
				{ code: 'CY', name: gettextCatalog.getString( 'Cyprus' ) },
				{ code: 'CZ', name: gettextCatalog.getString( 'Czech Republic' ) },
				{ code: 'CD', name: gettextCatalog.getString( 'Democratic Republic of the Congo' ) },
				{ code: 'DK', name: gettextCatalog.getString( 'Denmark' ) },
				{ code: 'DJ', name: gettextCatalog.getString( 'Djibouti' ) },
				{ code: 'DM', name: gettextCatalog.getString( 'Dominica' ) },
				{ code: 'DO', name: gettextCatalog.getString( 'Dominican Republic' ) },
				{ code: 'TL', name: gettextCatalog.getString( 'East Timor' ) },
				{ code: 'EC', name: gettextCatalog.getString( 'Ecuador' ) },
				{ code: 'EG', name: gettextCatalog.getString( 'Egypt' ) },
				{ code: 'SV', name: gettextCatalog.getString( 'El Salvador' ) },
				{ code: 'GQ', name: gettextCatalog.getString( 'Equatorial Guinea' ) },
				{ code: 'ER', name: gettextCatalog.getString( 'Eritrea' ) },
				{ code: 'EE', name: gettextCatalog.getString( 'Estonia' ) },
				{ code: 'ET', name: gettextCatalog.getString( 'Ethiopia' ) },
				{ code: 'FK', name: gettextCatalog.getString( 'Falkland Islands' ) },
				{ code: 'FO', name: gettextCatalog.getString( 'Faroe Islands' ) },
				{ code: 'FJ', name: gettextCatalog.getString( 'Fiji' ) },
				{ code: 'FI', name: gettextCatalog.getString( 'Finland' ) },
				{ code: 'FR', name: gettextCatalog.getString( 'France' ) },
				{ code: 'GF', name: gettextCatalog.getString( 'French Guiana' ) },
				{ code: 'PF', name: gettextCatalog.getString( 'French Polynesia' ) },
				{ code: 'TF', name: gettextCatalog.getString( 'French Southern Territories' ) },
				{ code: 'GA', name: gettextCatalog.getString( 'Gabon' ) },
				{ code: 'GM', name: gettextCatalog.getString( 'Gambia' ) },
				{ code: 'GE', name: gettextCatalog.getString( 'Georgia' ) },
				{ code: 'DE', name: gettextCatalog.getString( 'Germany' ) },
				{ code: 'GH', name: gettextCatalog.getString( 'Ghana' ) },
				{ code: 'GI', name: gettextCatalog.getString( 'Gibraltar' ) },
				{ code: 'GR', name: gettextCatalog.getString( 'Greece' ) },
				{ code: 'GL', name: gettextCatalog.getString( 'Greenland' ) },
				{ code: 'GD', name: gettextCatalog.getString( 'Grenada' ) },
				{ code: 'GP', name: gettextCatalog.getString( 'Guadeloupe' ) },
				{ code: 'GU', name: gettextCatalog.getString( 'Guam' ) },
				{ code: 'GT', name: gettextCatalog.getString( 'Guatemala' ) },
				{ code: 'GG', name: gettextCatalog.getString( 'Guernsey' ) },
				{ code: 'GN', name: gettextCatalog.getString( 'Guinea' ) },
				{ code: 'GW', name: gettextCatalog.getString( 'Guinea-Bissau' ) },
				{ code: 'GY', name: gettextCatalog.getString( 'Guyana' ) },
				{ code: 'HT', name: gettextCatalog.getString( 'Haiti' ) },
				{ code: 'HM', name: gettextCatalog.getString( 'Heard Island and McDonald Islands' ) },
				{ code: 'HN', name: gettextCatalog.getString( 'Honduras' ) },
				{ code: 'HK', name: gettextCatalog.getString( 'Hong Kong' ) },
				{ code: 'HU', name: gettextCatalog.getString( 'Hungary' ) },
				{ code: 'IS', name: gettextCatalog.getString( 'Iceland' ) },
				{ code: 'IN', name: gettextCatalog.getString( 'India' ) },
				{ code: 'ID', name: gettextCatalog.getString( 'Indonesia' ) },
				{ code: 'IR', name: gettextCatalog.getString( 'Iran' ) },
				{ code: 'IQ', name: gettextCatalog.getString( 'Iraq' ) },
				{ code: 'IE', name: gettextCatalog.getString( 'Ireland' ) },
				{ code: 'IM', name: gettextCatalog.getString( 'Isle of Man' ) },
				{ code: 'IL', name: gettextCatalog.getString( 'Israel' ) },
				{ code: 'IT', name: gettextCatalog.getString( 'Italy' ) },
				{ code: 'CI', name: gettextCatalog.getString( 'Ivory Coast' ) },
				{ code: 'JM', name: gettextCatalog.getString( 'Jamaica' ) },
				{ code: 'JP', name: gettextCatalog.getString( 'Japan' ) },
				{ code: 'JE', name: gettextCatalog.getString( 'Jersey' ) },
				{ code: 'JO', name: gettextCatalog.getString( 'Jordan' ) },
				{ code: 'KZ', name: gettextCatalog.getString( 'Kazakhstan' ) },
				{ code: 'KE', name: gettextCatalog.getString( 'Kenya' ) },
				{ code: 'KI', name: gettextCatalog.getString( 'Kiribati' ) },
				{ code: 'XK', name: gettextCatalog.getString( 'Kosovo' ) },
				{ code: 'KW', name: gettextCatalog.getString( 'Kuwait' ) },
				{ code: 'KG', name: gettextCatalog.getString( 'Kyrgyzstan' ) },
				{ code: 'LA', name: gettextCatalog.getString( 'Laos' ) },
				{ code: 'LV', name: gettextCatalog.getString( 'Latvia' ) },
				{ code: 'LB', name: gettextCatalog.getString( 'Lebanon' ) },
				{ code: 'LS', name: gettextCatalog.getString( 'Lesotho' ) },
				{ code: 'LR', name: gettextCatalog.getString( 'Liberia' ) },
				{ code: 'LY', name: gettextCatalog.getString( 'Libya' ) },
				{ code: 'LI', name: gettextCatalog.getString( 'Liechtenstein' ) },
				{ code: 'LT', name: gettextCatalog.getString( 'Lithuania' ) },
				{ code: 'LU', name: gettextCatalog.getString( 'Luxembourg' ) },
				{ code: 'MO', name: gettextCatalog.getString( 'Macao' ) },
				{ code: 'MK', name: gettextCatalog.getString( 'Macedonia' ) },
				{ code: 'MG', name: gettextCatalog.getString( 'Madagascar' ) },
				{ code: 'MW', name: gettextCatalog.getString( 'Malawi' ) },
				{ code: 'MY', name: gettextCatalog.getString( 'Malaysia' ) },
				{ code: 'MV', name: gettextCatalog.getString( 'Maldives' ) },
				{ code: 'ML', name: gettextCatalog.getString( 'Mali' ) },
				{ code: 'MT', name: gettextCatalog.getString( 'Malta' ) },
				{ code: 'MH', name: gettextCatalog.getString( 'Marshall Islands' ) },
				{ code: 'MQ', name: gettextCatalog.getString( 'Martinique' ) },
				{ code: 'MR', name: gettextCatalog.getString( 'Mauritania' ) },
				{ code: 'MU', name: gettextCatalog.getString( 'Mauritius' ) },
				{ code: 'YT', name: gettextCatalog.getString( 'Mayotte' ) },
				{ code: 'MX', name: gettextCatalog.getString( 'Mexico' ) },
				{ code: 'FM', name: gettextCatalog.getString( 'Micronesia' ) },
				{ code: 'MD', name: gettextCatalog.getString( 'Moldova' ) },
				{ code: 'MC', name: gettextCatalog.getString( 'Monaco' ) },
				{ code: 'MN', name: gettextCatalog.getString( 'Mongolia' ) },
				{ code: 'ME', name: gettextCatalog.getString( 'Montenegro' ) },
				{ code: 'MS', name: gettextCatalog.getString( 'Montserrat' ) },
				{ code: 'MA', name: gettextCatalog.getString( 'Morocco' ) },
				{ code: 'MZ', name: gettextCatalog.getString( 'Mozambique' ) },
				{ code: 'MM', name: gettextCatalog.getString( 'Myanmar' ) },
				{ code: 'NA', name: gettextCatalog.getString( 'Namibia' ) },
				{ code: 'NR', name: gettextCatalog.getString( 'Nauru' ) },
				{ code: 'NP', name: gettextCatalog.getString( 'Nepal' ) },
				{ code: 'NL', name: gettextCatalog.getString( 'Netherlands' ) },
				{ code: 'NC', name: gettextCatalog.getString( 'New Caledonia' ) },
				{ code: 'NZ', name: gettextCatalog.getString( 'New Zealand' ) },
				{ code: 'NI', name: gettextCatalog.getString( 'Nicaragua' ) },
				{ code: 'NE', name: gettextCatalog.getString( 'Niger' ) },
				{ code: 'NG', name: gettextCatalog.getString( 'Nigeria' ) },
				{ code: 'NU', name: gettextCatalog.getString( 'Niue' ) },
				{ code: 'NF', name: gettextCatalog.getString( 'Norfolk Island' ) },
				{ code: 'KP', name: gettextCatalog.getString( 'North Korea' ) },
				{ code: 'MP', name: gettextCatalog.getString( 'Northern Mariana Islands' ) },
				{ code: 'NO', name: gettextCatalog.getString( 'Norway' ) },
				{ code: 'OM', name: gettextCatalog.getString( 'Oman' ) },
				{ code: 'PK', name: gettextCatalog.getString( 'Pakistan' ) },
				{ code: 'PW', name: gettextCatalog.getString( 'Palau' ) },
				{ code: 'PS', name: gettextCatalog.getString( 'Palestinian Territory' ) },
				{ code: 'PA', name: gettextCatalog.getString( 'Panama' ) },
				{ code: 'PG', name: gettextCatalog.getString( 'Papua New Guinea' ) },
				{ code: 'PY', name: gettextCatalog.getString( 'Paraguay' ) },
				{ code: 'PE', name: gettextCatalog.getString( 'Peru' ) },
				{ code: 'PH', name: gettextCatalog.getString( 'Philippines' ) },
				{ code: 'PN', name: gettextCatalog.getString( 'Pitcairn' ) },
				{ code: 'PL', name: gettextCatalog.getString( 'Poland' ) },
				{ code: 'PT', name: gettextCatalog.getString( 'Portugal' ) },
				{ code: 'PR', name: gettextCatalog.getString( 'Puerto Rico' ) },
				{ code: 'QA', name: gettextCatalog.getString( 'Qatar' ) },
				{ code: 'CG', name: gettextCatalog.getString( 'Republic of the Congo' ) },
				{ code: 'RE', name: gettextCatalog.getString( 'Reunion' ) },
				{ code: 'RO', name: gettextCatalog.getString( 'Romania' ) },
				{ code: 'RU', name: gettextCatalog.getString( 'Russia' ) },
				{ code: 'RW', name: gettextCatalog.getString( 'Rwanda' ) },
				{ code: 'BL', name: gettextCatalog.getString( 'Saint Barthelemy' ) },
				{ code: 'SH', name: gettextCatalog.getString( 'Saint Helena' ) },
				{ code: 'KN', name: gettextCatalog.getString( 'Saint Kitts and Nevis' ) },
				{ code: 'LC', name: gettextCatalog.getString( 'Saint Lucia' ) },
				{ code: 'MF', name: gettextCatalog.getString( 'Saint Martin' ) },
				{ code: 'PM', name: gettextCatalog.getString( 'Saint Pierre and Miquelon' ) },
				{ code: 'VC', name: gettextCatalog.getString( 'Saint Vincent and the Grenadines' ) },
				{ code: 'WS', name: gettextCatalog.getString( 'Samoa' ) },
				{ code: 'SM', name: gettextCatalog.getString( 'San Marino' ) },
				{ code: 'ST', name: gettextCatalog.getString( 'Sao Tome and Principe' ) },
				{ code: 'SA', name: gettextCatalog.getString( 'Saudi Arabia' ) },
				{ code: 'SN', name: gettextCatalog.getString( 'Senegal' ) },
				{ code: 'RS', name: gettextCatalog.getString( 'Serbia' ) },
				{ code: 'SC', name: gettextCatalog.getString( 'Seychelles' ) },
				{ code: 'SL', name: gettextCatalog.getString( 'Sierra Leone' ) },
				{ code: 'SG', name: gettextCatalog.getString( 'Singapore' ) },
				{ code: 'SX', name: gettextCatalog.getString( 'Sint Maarten' ) },
				{ code: 'SK', name: gettextCatalog.getString( 'Slovakia' ) },
				{ code: 'SI', name: gettextCatalog.getString( 'Slovenia' ) },
				{ code: 'SB', name: gettextCatalog.getString( 'Solomon Islands' ) },
				{ code: 'SO', name: gettextCatalog.getString( 'Somalia' ) },
				{ code: 'ZA', name: gettextCatalog.getString( 'South Africa' ) },
				{ code: 'GS', name: gettextCatalog.getString( 'South Georgia and the South Sandwich Islands' ) },
				{ code: 'KR', name: gettextCatalog.getString( 'South Korea' ) },
				{ code: 'SS', name: gettextCatalog.getString( 'South Sudan' ) },
				{ code: 'ES', name: gettextCatalog.getString( 'Spain' ) },
				{ code: 'LK', name: gettextCatalog.getString( 'Sri Lanka' ) },
				{ code: 'SD', name: gettextCatalog.getString( 'Sudan' ) },
				{ code: 'SR', name: gettextCatalog.getString( 'Suriname' ) },
				{ code: 'SJ', name: gettextCatalog.getString( 'Svalbard and Jan Mayen' ) },
				{ code: 'SZ', name: gettextCatalog.getString( 'Swaziland' ) },
				{ code: 'SE', name: gettextCatalog.getString( 'Sweden' ) },
				{ code: 'CH', name: gettextCatalog.getString( 'Switzerland' ) },
				{ code: 'SY', name: gettextCatalog.getString( 'Syria' ) },
				{ code: 'TW', name: gettextCatalog.getString( 'Taiwan' ) },
				{ code: 'TJ', name: gettextCatalog.getString( 'Tajikistan' ) },
				{ code: 'TZ', name: gettextCatalog.getString( 'Tanzania' ) },
				{ code: 'TH', name: gettextCatalog.getString( 'Thailand' ) },
				{ code: 'TG', name: gettextCatalog.getString( 'Togo' ) },
				{ code: 'TK', name: gettextCatalog.getString( 'Tokelau' ) },
				{ code: 'TO', name: gettextCatalog.getString( 'Tonga' ) },
				{ code: 'TT', name: gettextCatalog.getString( 'Trinidad and Tobago' ) },
				{ code: 'TN', name: gettextCatalog.getString( 'Tunisia' ) },
				{ code: 'TR', name: gettextCatalog.getString( 'Turkey' ) },
				{ code: 'TM', name: gettextCatalog.getString( 'Turkmenistan' ) },
				{ code: 'TC', name: gettextCatalog.getString( 'Turks and Caicos Islands' ) },
				{ code: 'TV', name: gettextCatalog.getString( 'Tuvalu' ) },
				{ code: 'VI', name: gettextCatalog.getString( 'U.S. Virgin Islands' ) },
				{ code: 'UG', name: gettextCatalog.getString( 'Uganda' ) },
				{ code: 'UA', name: gettextCatalog.getString( 'Ukraine' ) },
				{ code: 'AE', name: gettextCatalog.getString( 'United Arab Emirates' ) },
				{ code: 'GB', name: gettextCatalog.getString( 'United Kingdom' ) },
				{ code: 'US', name: gettextCatalog.getString( 'United States' ) },
				{ code: 'UM', name: gettextCatalog.getString( 'United States Minor Outlying Islands' ) },
				{ code: 'UY', name: gettextCatalog.getString( 'Uruguay' ) },
				{ code: 'UZ', name: gettextCatalog.getString( 'Uzbekistan' ) },
				{ code: 'VU', name: gettextCatalog.getString( 'Vanuatu' ) },
				{ code: 'VA', name: gettextCatalog.getString( 'Vatican' ) },
				{ code: 'VE', name: gettextCatalog.getString( 'Venezuela' ) },
				{ code: 'VN', name: gettextCatalog.getString( 'Vietnam' ) },
				{ code: 'WF', name: gettextCatalog.getString( 'Wallis and Futuna' ) },
				{ code: 'EH', name: gettextCatalog.getString( 'Western Sahara' ) },
				{ code: 'YE', name: gettextCatalog.getString( 'Yemen' ) },
				{ code: 'ZM', name: gettextCatalog.getString( 'Zambia' ) },
				{ code: 'ZW', name: gettextCatalog.getString( 'Zimbabwe' ) },
			];
		}

		return _countries;
	};

	this.getRegions = function( country )
	{
		if ( !_regions[ country ] ) {
			if ( country == 'US' ) {
				_regions[ country ] = [
					{ code: 'AL', name: gettextCatalog.getString( 'Alabama' ) },
					{ code: 'AK', name: gettextCatalog.getString( 'Alaska' ) },
					{ code: 'AZ', name: gettextCatalog.getString( 'Arizona' ) },
					{ code: 'AR', name: gettextCatalog.getString( 'Arkansas' ) },
					{ code: 'CA', name: gettextCatalog.getString( 'California' ) },
					{ code: 'CO', name: gettextCatalog.getString( 'Colorado' ) },
					{ code: 'CT', name: gettextCatalog.getString( 'Connecticut' ) },
					{ code: 'DE', name: gettextCatalog.getString( 'Delaware' ) },
					{ code: 'FL', name: gettextCatalog.getString( 'Florida' ) },
					{ code: 'GA', name: gettextCatalog.getString( 'Georgia' ) },
					{ code: 'HI', name: gettextCatalog.getString( 'Hawaii' ) },
					{ code: 'ID', name: gettextCatalog.getString( 'Idaho' ) },
					{ code: 'IL', name: gettextCatalog.getString( 'Illinois' ) },
					{ code: 'IN', name: gettextCatalog.getString( 'Indiana' ) },
					{ code: 'IA', name: gettextCatalog.getString( 'Iowa' ) },
					{ code: 'KS', name: gettextCatalog.getString( 'Kansas' ) },
					{ code: 'KY', name: gettextCatalog.getString( 'Kentucky' ) },
					{ code: 'LA', name: gettextCatalog.getString( 'Louisiana' ) },
					{ code: 'ME', name: gettextCatalog.getString( 'Maine' ) },
					{ code: 'MD', name: gettextCatalog.getString( 'Maryland' ) },
					{ code: 'MA', name: gettextCatalog.getString( 'Massachusetts' ) },
					{ code: 'MI', name: gettextCatalog.getString( 'Michigan' ) },
					{ code: 'MN', name: gettextCatalog.getString( 'Minnesota' ) },
					{ code: 'MS', name: gettextCatalog.getString( 'Mississippi' ) },
					{ code: 'MO', name: gettextCatalog.getString( 'Missouri' ) },
					{ code: 'MT', name: gettextCatalog.getString( 'Montana' ) },
					{ code: 'NE', name: gettextCatalog.getString( 'Nebraska' ) },
					{ code: 'NV', name: gettextCatalog.getString( 'Nevada' ) },
					{ code: 'NH', name: gettextCatalog.getString( 'New Hampshire' ) },
					{ code: 'NJ', name: gettextCatalog.getString( 'New Jersey' ) },
					{ code: 'NM', name: gettextCatalog.getString( 'New Mexico' ) },
					{ code: 'NY', name: gettextCatalog.getString( 'New York' ) },
					{ code: 'NC', name: gettextCatalog.getString( 'North Carolina' ) },
					{ code: 'ND', name: gettextCatalog.getString( 'North Dakota' ) },
					{ code: 'OH', name: gettextCatalog.getString( 'Ohio' ) },
					{ code: 'OK', name: gettextCatalog.getString( 'Oklahoma' ) },
					{ code: 'OR', name: gettextCatalog.getString( 'Oregon' ) },
					{ code: 'PA', name: gettextCatalog.getString( 'Pennsylvania' ) },
					{ code: 'RI', name: gettextCatalog.getString( 'Rhode Island' ) },
					{ code: 'SC', name: gettextCatalog.getString( 'South Carolina' ) },
					{ code: 'SD', name: gettextCatalog.getString( 'South Dakota' ) },
					{ code: 'TN', name: gettextCatalog.getString( 'Tennessee' ) },
					{ code: 'TX', name: gettextCatalog.getString( 'Texas' ) },
					{ code: 'UT', name: gettextCatalog.getString( 'Utah' ) },
					{ code: 'VT', name: gettextCatalog.getString( 'Vermont' ) },
					{ code: 'VA', name: gettextCatalog.getString( 'Virginia' ) },
					{ code: 'WA', name: gettextCatalog.getString( 'Washington' ) },
					{ code: 'WV', name: gettextCatalog.getString( 'West Virginia' ) },
					{ code: 'WI', name: gettextCatalog.getString( 'Wisconsin' ) },
					{ code: 'WY', name: gettextCatalog.getString( 'Wyoming' ) },
					{ code: 'DC', name: gettextCatalog.getString( 'Washington D.C.' ) },
					{ code: 'AS', name: gettextCatalog.getString( 'American Samoa' ) },
					{ code: 'GU', name: gettextCatalog.getString( 'Guam' ) },
					{ code: 'MP', name: gettextCatalog.getString( 'Northern Mariana Islands' ) },
					{ code: 'PR', name: gettextCatalog.getString( 'Puerto Rico' ) },
					{ code: 'VI', name: gettextCatalog.getString( 'U.S. Virgin Islands' ) },
				];
			}
			else if ( country == 'CA' ) {
				_regions[ country ] = [
					{ code: 'ON', name: 'Ontario' },
					{ code: 'QC', name: 'Quebec' },
					{ code: 'NS', name: 'Nova Scotia' },
					{ code: 'NB', name: 'New Brunswick' },
					{ code: 'MB', name: 'Manitoba' },
					{ code: 'BC', name: 'British Columbia' },
					{ code: 'PE', name: 'Prince Edward Island' },
					{ code: 'SK', name: 'Saskatchewan' },
					{ code: 'AB', name: 'Alberta' },
					{ code: 'NL', name: 'Newfoundland and Labrador' },
					{ code: 'NT', name: 'Northwest Territories' },
					{ code: 'YT', name: 'Yukon' },
					{ code: 'NU', name: 'Nunavut' },
				];
			}
			// else if ( country == '' ) {
			// 	_regions[ country ] = [

			// 	];
			// }
		}

		return _regions[ country ];
	};
} );
