import { Translate } from '../translate/translate';

interface Country
{
	code: string;
	name: string;
}

interface Region
{
	code: string;
	name: string;
}

export class Geo
{
	private static countries: Country[] = [];
	private static regions: { [k: string]: Region[] } = {};

	static getCountryName( code: string )
	{
		const country = this.getCountries().find( ( c ) => c.code === (code || '').toLowerCase() );
		return country ? country.name : undefined;
	}

	static getRegionName( country: string, code: string )
	{
		const regions = this.getRegions( country );
		if ( !regions ) {
			console.log( 'no region' );
			return undefined;
		}

		const region = regions.find( ( c ) => c.code === (code || '').toLowerCase() );
		return region ? region.name : undefined;
	}

	static getCountries()
	{
		if ( !this.countries.length ) {
			this.countries = [
				{ code: 'af', name: Translate.translate( 'Afghanistan' ) },
				{ code: 'ax', name: Translate.translate( 'Aland Islands' ) },
				{ code: 'al', name: Translate.translate( 'Albania' ) },
				{ code: 'dz', name: Translate.translate( 'Algeria' ) },
				{ code: 'as', name: Translate.translate( 'American Samoa' ) },
				{ code: 'ad', name: Translate.translate( 'Andorra' ) },
				{ code: 'ao', name: Translate.translate( 'Angola' ) },
				{ code: 'ai', name: Translate.translate( 'Anguilla' ) },
				{ code: 'aq', name: Translate.translate( 'Antarctica' ) },
				{ code: 'ag', name: Translate.translate( 'Antigua and Barbuda' ) },
				{ code: 'ar', name: Translate.translate( 'Argentina' ) },
				{ code: 'am', name: Translate.translate( 'Armenia' ) },
				{ code: 'aw', name: Translate.translate( 'Aruba' ) },
				{ code: 'au', name: Translate.translate( 'Australia' ) },
				{ code: 'at', name: Translate.translate( 'Austria' ) },
				{ code: 'az', name: Translate.translate( 'Azerbaijan' ) },
				{ code: 'bs', name: Translate.translate( 'Bahamas' ) },
				{ code: 'bh', name: Translate.translate( 'Bahrain' ) },
				{ code: 'bd', name: Translate.translate( 'Bangladesh' ) },
				{ code: 'bb', name: Translate.translate( 'Barbados' ) },
				{ code: 'by', name: Translate.translate( 'Belarus' ) },
				{ code: 'be', name: Translate.translate( 'Belgium' ) },
				{ code: 'bz', name: Translate.translate( 'Belize' ) },
				{ code: 'bj', name: Translate.translate( 'Benin' ) },
				{ code: 'bm', name: Translate.translate( 'Bermuda' ) },
				{ code: 'bt', name: Translate.translate( 'Bhutan' ) },
				{ code: 'bo', name: Translate.translate( 'Bolivia' ) },
				{ code: 'bq', name: Translate.translate( 'Bonaire, Saint Eustatius and Saba' ) },
				{ code: 'ba', name: Translate.translate( 'Bosnia and Herzegovina' ) },
				{ code: 'bw', name: Translate.translate( 'Botswana' ) },
				{ code: 'bv', name: Translate.translate( 'Bouvet Island' ) },
				{ code: 'br', name: Translate.translate( 'Brazil' ) },
				{ code: 'io', name: Translate.translate( 'British Indian Ocean Territory' ) },
				{ code: 'vg', name: Translate.translate( 'British Virgin Islands' ) },
				{ code: 'bn', name: Translate.translate( 'Brunei' ) },
				{ code: 'bg', name: Translate.translate( 'Bulgaria' ) },
				{ code: 'bf', name: Translate.translate( 'Burkina Faso' ) },
				{ code: 'bi', name: Translate.translate( 'Burundi' ) },
				{ code: 'kh', name: Translate.translate( 'Cambodia' ) },
				{ code: 'cm', name: Translate.translate( 'Cameroon' ) },
				{ code: 'ca', name: Translate.translate( 'Canada' ) },
				{ code: 'cv', name: Translate.translate( 'Cape Verde' ) },
				{ code: 'ky', name: Translate.translate( 'Cayman Islands' ) },
				{ code: 'cf', name: Translate.translate( 'Central African Republic' ) },
				{ code: 'td', name: Translate.translate( 'Chad' ) },
				{ code: 'cl', name: Translate.translate( 'Chile' ) },
				{ code: 'cn', name: Translate.translate( 'China' ) },
				{ code: 'cx', name: Translate.translate( 'Christmas Island' ) },
				{ code: 'cc', name: Translate.translate( 'Cocos Islands' ) },
				{ code: 'co', name: Translate.translate( 'Colombia' ) },
				{ code: 'km', name: Translate.translate( 'Comoros' ) },
				{ code: 'ck', name: Translate.translate( 'Cook Islands' ) },
				{ code: 'cr', name: Translate.translate( 'Costa Rica' ) },
				{ code: 'hr', name: Translate.translate( 'Croatia' ) },
				{ code: 'cu', name: Translate.translate( 'Cuba' ) },
				{ code: 'cw', name: Translate.translate( 'Curacao' ) },
				{ code: 'cy', name: Translate.translate( 'Cyprus' ) },
				{ code: 'cz', name: Translate.translate( 'Czech Republic' ) },
				{ code: 'cd', name: Translate.translate( 'Democratic Republic of the Congo' ) },
				{ code: 'dk', name: Translate.translate( 'Denmark' ) },
				{ code: 'dj', name: Translate.translate( 'Djibouti' ) },
				{ code: 'dm', name: Translate.translate( 'Dominica' ) },
				{ code: 'do', name: Translate.translate( 'Dominican Republic' ) },
				{ code: 'tl', name: Translate.translate( 'East Timor' ) },
				{ code: 'ec', name: Translate.translate( 'Ecuador' ) },
				{ code: 'eg', name: Translate.translate( 'Egypt' ) },
				{ code: 'sv', name: Translate.translate( 'El Salvador' ) },
				{ code: 'gq', name: Translate.translate( 'Equatorial Guinea' ) },
				{ code: 'er', name: Translate.translate( 'Eritrea' ) },
				{ code: 'ee', name: Translate.translate( 'Estonia' ) },
				{ code: 'et', name: Translate.translate( 'Ethiopia' ) },
				{ code: 'fk', name: Translate.translate( 'Falkland Islands' ) },
				{ code: 'fo', name: Translate.translate( 'Faroe Islands' ) },
				{ code: 'fj', name: Translate.translate( 'Fiji' ) },
				{ code: 'fi', name: Translate.translate( 'Finland' ) },
				{ code: 'fr', name: Translate.translate( 'France' ) },
				{ code: 'gf', name: Translate.translate( 'French Guiana' ) },
				{ code: 'pf', name: Translate.translate( 'French Polynesia' ) },
				{ code: 'tf', name: Translate.translate( 'French Southern Territories' ) },
				{ code: 'ga', name: Translate.translate( 'Gabon' ) },
				{ code: 'gm', name: Translate.translate( 'Gambia' ) },
				{ code: 'ge', name: Translate.translate( 'Georgia' ) },
				{ code: 'de', name: Translate.translate( 'Germany' ) },
				{ code: 'gh', name: Translate.translate( 'Ghana' ) },
				{ code: 'gi', name: Translate.translate( 'Gibraltar' ) },
				{ code: 'gr', name: Translate.translate( 'Greece' ) },
				{ code: 'gl', name: Translate.translate( 'Greenland' ) },
				{ code: 'gd', name: Translate.translate( 'Grenada' ) },
				{ code: 'gp', name: Translate.translate( 'Guadeloupe' ) },
				{ code: 'gu', name: Translate.translate( 'Guam' ) },
				{ code: 'gt', name: Translate.translate( 'Guatemala' ) },
				{ code: 'gg', name: Translate.translate( 'Guernsey' ) },
				{ code: 'gn', name: Translate.translate( 'Guinea' ) },
				{ code: 'gw', name: Translate.translate( 'Guinea-Bissau' ) },
				{ code: 'gy', name: Translate.translate( 'Guyana' ) },
				{ code: 'ht', name: Translate.translate( 'Haiti' ) },
				{ code: 'hm', name: Translate.translate( 'Heard Island and McDonald Islands' ) },
				{ code: 'hn', name: Translate.translate( 'Honduras' ) },
				{ code: 'hk', name: Translate.translate( 'Hong Kong' ) },
				{ code: 'hu', name: Translate.translate( 'Hungary' ) },
				{ code: 'is', name: Translate.translate( 'Iceland' ) },
				{ code: 'in', name: Translate.translate( 'India' ) },
				{ code: 'id', name: Translate.translate( 'Indonesia' ) },
				{ code: 'ir', name: Translate.translate( 'Iran' ) },
				{ code: 'iq', name: Translate.translate( 'Iraq' ) },
				{ code: 'ie', name: Translate.translate( 'Ireland' ) },
				{ code: 'im', name: Translate.translate( 'Isle of Man' ) },
				{ code: 'il', name: Translate.translate( 'Israel' ) },
				{ code: 'it', name: Translate.translate( 'Italy' ) },
				{ code: 'ci', name: Translate.translate( 'Ivory Coast' ) },
				{ code: 'jm', name: Translate.translate( 'Jamaica' ) },
				{ code: 'jp', name: Translate.translate( 'Japan' ) },
				{ code: 'je', name: Translate.translate( 'Jersey' ) },
				{ code: 'jo', name: Translate.translate( 'Jordan' ) },
				{ code: 'kz', name: Translate.translate( 'Kazakhstan' ) },
				{ code: 'ke', name: Translate.translate( 'Kenya' ) },
				{ code: 'ki', name: Translate.translate( 'Kiribati' ) },
				{ code: 'xk', name: Translate.translate( 'Kosovo' ) },
				{ code: 'kw', name: Translate.translate( 'Kuwait' ) },
				{ code: 'kg', name: Translate.translate( 'Kyrgyzstan' ) },
				{ code: 'la', name: Translate.translate( 'Laos' ) },
				{ code: 'lv', name: Translate.translate( 'Latvia' ) },
				{ code: 'lb', name: Translate.translate( 'Lebanon' ) },
				{ code: 'ls', name: Translate.translate( 'Lesotho' ) },
				{ code: 'lr', name: Translate.translate( 'Liberia' ) },
				{ code: 'ly', name: Translate.translate( 'Libya' ) },
				{ code: 'li', name: Translate.translate( 'Liechtenstein' ) },
				{ code: 'lt', name: Translate.translate( 'Lithuania' ) },
				{ code: 'lu', name: Translate.translate( 'Luxembourg' ) },
				{ code: 'mo', name: Translate.translate( 'Macao' ) },
				{ code: 'mk', name: Translate.translate( 'Macedonia' ) },
				{ code: 'mg', name: Translate.translate( 'Madagascar' ) },
				{ code: 'mw', name: Translate.translate( 'Malawi' ) },
				{ code: 'my', name: Translate.translate( 'Malaysia' ) },
				{ code: 'mv', name: Translate.translate( 'Maldives' ) },
				{ code: 'ml', name: Translate.translate( 'Mali' ) },
				{ code: 'mt', name: Translate.translate( 'Malta' ) },
				{ code: 'mh', name: Translate.translate( 'Marshall Islands' ) },
				{ code: 'mq', name: Translate.translate( 'Martinique' ) },
				{ code: 'mr', name: Translate.translate( 'Mauritania' ) },
				{ code: 'mu', name: Translate.translate( 'Mauritius' ) },
				{ code: 'yt', name: Translate.translate( 'Mayotte' ) },
				{ code: 'mx', name: Translate.translate( 'Mexico' ) },
				{ code: 'fm', name: Translate.translate( 'Micronesia' ) },
				{ code: 'md', name: Translate.translate( 'Moldova' ) },
				{ code: 'mc', name: Translate.translate( 'Monaco' ) },
				{ code: 'mn', name: Translate.translate( 'Mongolia' ) },
				{ code: 'me', name: Translate.translate( 'Montenegro' ) },
				{ code: 'ms', name: Translate.translate( 'Montserrat' ) },
				{ code: 'ma', name: Translate.translate( 'Morocco' ) },
				{ code: 'mz', name: Translate.translate( 'Mozambique' ) },
				{ code: 'mm', name: Translate.translate( 'Myanmar' ) },
				{ code: 'na', name: Translate.translate( 'Namibia' ) },
				{ code: 'nr', name: Translate.translate( 'Nauru' ) },
				{ code: 'np', name: Translate.translate( 'Nepal' ) },
				{ code: 'nl', name: Translate.translate( 'Netherlands' ) },
				{ code: 'nc', name: Translate.translate( 'New Caledonia' ) },
				{ code: 'nz', name: Translate.translate( 'New Zealand' ) },
				{ code: 'ni', name: Translate.translate( 'Nicaragua' ) },
				{ code: 'ne', name: Translate.translate( 'Niger' ) },
				{ code: 'ng', name: Translate.translate( 'Nigeria' ) },
				{ code: 'nu', name: Translate.translate( 'Niue' ) },
				{ code: 'nf', name: Translate.translate( 'Norfolk Island' ) },
				{ code: 'kp', name: Translate.translate( 'North Korea' ) },
				{ code: 'mp', name: Translate.translate( 'Northern Mariana Islands' ) },
				{ code: 'no', name: Translate.translate( 'Norway' ) },
				{ code: 'om', name: Translate.translate( 'Oman' ) },
				{ code: 'pk', name: Translate.translate( 'Pakistan' ) },
				{ code: 'pw', name: Translate.translate( 'Palau' ) },
				{ code: 'ps', name: Translate.translate( 'Palestinian Territory' ) },
				{ code: 'pa', name: Translate.translate( 'Panama' ) },
				{ code: 'pg', name: Translate.translate( 'Papua New Guinea' ) },
				{ code: 'py', name: Translate.translate( 'Paraguay' ) },
				{ code: 'pe', name: Translate.translate( 'Peru' ) },
				{ code: 'ph', name: Translate.translate( 'Philippines' ) },
				{ code: 'pn', name: Translate.translate( 'Pitcairn' ) },
				{ code: 'pl', name: Translate.translate( 'Poland' ) },
				{ code: 'pt', name: Translate.translate( 'Portugal' ) },
				{ code: 'pr', name: Translate.translate( 'Puerto Rico' ) },
				{ code: 'qa', name: Translate.translate( 'Qatar' ) },
				{ code: 'cg', name: Translate.translate( 'Republic of the Congo' ) },
				{ code: 're', name: Translate.translate( 'Reunion' ) },
				{ code: 'ro', name: Translate.translate( 'Romania' ) },
				{ code: 'ru', name: Translate.translate( 'Russia' ) },
				{ code: 'rw', name: Translate.translate( 'Rwanda' ) },
				{ code: 'bl', name: Translate.translate( 'Saint Barthelemy' ) },
				{ code: 'sh', name: Translate.translate( 'Saint Helena' ) },
				{ code: 'kn', name: Translate.translate( 'Saint Kitts and Nevis' ) },
				{ code: 'lc', name: Translate.translate( 'Saint Lucia' ) },
				{ code: 'mf', name: Translate.translate( 'Saint Martin' ) },
				{ code: 'pm', name: Translate.translate( 'Saint Pierre and Miquelon' ) },
				{ code: 'vc', name: Translate.translate( 'Saint Vincent and the Grenadines' ) },
				{ code: 'ws', name: Translate.translate( 'Samoa' ) },
				{ code: 'sm', name: Translate.translate( 'San Marino' ) },
				{ code: 'st', name: Translate.translate( 'Sao Tome and Principe' ) },
				{ code: 'sa', name: Translate.translate( 'Saudi Arabia' ) },
				{ code: 'sn', name: Translate.translate( 'Senegal' ) },
				{ code: 'rs', name: Translate.translate( 'Serbia' ) },
				{ code: 'sc', name: Translate.translate( 'Seychelles' ) },
				{ code: 'sl', name: Translate.translate( 'Sierra Leone' ) },
				{ code: 'sg', name: Translate.translate( 'Singapore' ) },
				{ code: 'sx', name: Translate.translate( 'Sint Maarten' ) },
				{ code: 'sk', name: Translate.translate( 'Slovakia' ) },
				{ code: 'si', name: Translate.translate( 'Slovenia' ) },
				{ code: 'sb', name: Translate.translate( 'Solomon Islands' ) },
				{ code: 'so', name: Translate.translate( 'Somalia' ) },
				{ code: 'za', name: Translate.translate( 'South Africa' ) },
				{ code: 'gs', name: Translate.translate( 'South Georgia and the South Sandwich Islands' ) },
				{ code: 'kr', name: Translate.translate( 'South Korea' ) },
				{ code: 'ss', name: Translate.translate( 'South Sudan' ) },
				{ code: 'es', name: Translate.translate( 'Spain' ) },
				{ code: 'lk', name: Translate.translate( 'Sri Lanka' ) },
				{ code: 'sd', name: Translate.translate( 'Sudan' ) },
				{ code: 'sr', name: Translate.translate( 'Suriname' ) },
				{ code: 'sj', name: Translate.translate( 'Svalbard and Jan Mayen' ) },
				{ code: 'sz', name: Translate.translate( 'Swaziland' ) },
				{ code: 'se', name: Translate.translate( 'Sweden' ) },
				{ code: 'ch', name: Translate.translate( 'Switzerland' ) },
				{ code: 'sy', name: Translate.translate( 'Syria' ) },
				{ code: 'tw', name: Translate.translate( 'Taiwan' ) },
				{ code: 'tj', name: Translate.translate( 'Tajikistan' ) },
				{ code: 'tz', name: Translate.translate( 'Tanzania' ) },
				{ code: 'th', name: Translate.translate( 'Thailand' ) },
				{ code: 'tg', name: Translate.translate( 'Togo' ) },
				{ code: 'tk', name: Translate.translate( 'Tokelau' ) },
				{ code: 'to', name: Translate.translate( 'Tonga' ) },
				{ code: 'tt', name: Translate.translate( 'Trinidad and Tobago' ) },
				{ code: 'tn', name: Translate.translate( 'Tunisia' ) },
				{ code: 'tr', name: Translate.translate( 'Turkey' ) },
				{ code: 'tm', name: Translate.translate( 'Turkmenistan' ) },
				{ code: 'tc', name: Translate.translate( 'Turks and Caicos Islands' ) },
				{ code: 'tv', name: Translate.translate( 'Tuvalu' ) },
				{ code: 'vi', name: Translate.translate( 'U.S. Virgin Islands' ) },
				{ code: 'ug', name: Translate.translate( 'Uganda' ) },
				{ code: 'ua', name: Translate.translate( 'Ukraine' ) },
				{ code: 'ae', name: Translate.translate( 'United Arab Emirates' ) },
				{ code: 'gb', name: Translate.translate( 'United Kingdom' ) },
				{ code: 'us', name: Translate.translate( 'United States' ) },
				{ code: 'um', name: Translate.translate( 'United States Minor Outlying Islands' ) },
				{ code: 'uy', name: Translate.translate( 'Uruguay' ) },
				{ code: 'uz', name: Translate.translate( 'Uzbekistan' ) },
				{ code: 'vu', name: Translate.translate( 'Vanuatu' ) },
				{ code: 'va', name: Translate.translate( 'Vatican' ) },
				{ code: 've', name: Translate.translate( 'Venezuela' ) },
				{ code: 'vn', name: Translate.translate( 'Vietnam' ) },
				{ code: 'wf', name: Translate.translate( 'Wallis and Futuna' ) },
				{ code: 'eh', name: Translate.translate( 'Western Sahara' ) },
				{ code: 'ye', name: Translate.translate( 'Yemen' ) },
				{ code: 'zm', name: Translate.translate( 'Zambia' ) },
				{ code: 'zw', name: Translate.translate( 'Zimbabwe' ) },
			];
		}

		return this.countries;
	}

	static getRegions( country: string ): Region[] | undefined
	{
		if ( !this.regions[ country ] ) {
			if ( country === 'us' ) {
				this.regions[ country ] = [
					{ code: 'al', name: Translate.translate( 'Alabama' ) },
					{ code: 'ak', name: Translate.translate( 'Alaska' ) },
					{ code: 'az', name: Translate.translate( 'Arizona' ) },
					{ code: 'ar', name: Translate.translate( 'Arkansas' ) },
					{ code: 'ca', name: Translate.translate( 'California' ) },
					{ code: 'co', name: Translate.translate( 'Colorado' ) },
					{ code: 'ct', name: Translate.translate( 'Connecticut' ) },
					{ code: 'de', name: Translate.translate( 'Delaware' ) },
					{ code: 'fl', name: Translate.translate( 'Florida' ) },
					{ code: 'ga', name: Translate.translate( 'Georgia' ) },
					{ code: 'hi', name: Translate.translate( 'Hawaii' ) },
					{ code: 'id', name: Translate.translate( 'Idaho' ) },
					{ code: 'il', name: Translate.translate( 'Illinois' ) },
					{ code: 'in', name: Translate.translate( 'Indiana' ) },
					{ code: 'ia', name: Translate.translate( 'Iowa' ) },
					{ code: 'ks', name: Translate.translate( 'Kansas' ) },
					{ code: 'ky', name: Translate.translate( 'Kentucky' ) },
					{ code: 'la', name: Translate.translate( 'Louisiana' ) },
					{ code: 'me', name: Translate.translate( 'Maine' ) },
					{ code: 'md', name: Translate.translate( 'Maryland' ) },
					{ code: 'ma', name: Translate.translate( 'Massachusetts' ) },
					{ code: 'mi', name: Translate.translate( 'Michigan' ) },
					{ code: 'mn', name: Translate.translate( 'Minnesota' ) },
					{ code: 'ms', name: Translate.translate( 'Mississippi' ) },
					{ code: 'mo', name: Translate.translate( 'Missouri' ) },
					{ code: 'mt', name: Translate.translate( 'Montana' ) },
					{ code: 'ne', name: Translate.translate( 'Nebraska' ) },
					{ code: 'nv', name: Translate.translate( 'Nevada' ) },
					{ code: 'nh', name: Translate.translate( 'New Hampshire' ) },
					{ code: 'nj', name: Translate.translate( 'New Jersey' ) },
					{ code: 'nm', name: Translate.translate( 'New Mexico' ) },
					{ code: 'ny', name: Translate.translate( 'New York' ) },
					{ code: 'nc', name: Translate.translate( 'North Carolina' ) },
					{ code: 'nd', name: Translate.translate( 'North Dakota' ) },
					{ code: 'oh', name: Translate.translate( 'Ohio' ) },
					{ code: 'ok', name: Translate.translate( 'Oklahoma' ) },
					{ code: 'or', name: Translate.translate( 'Oregon' ) },
					{ code: 'pa', name: Translate.translate( 'Pennsylvania' ) },
					{ code: 'ri', name: Translate.translate( 'Rhode Island' ) },
					{ code: 'sc', name: Translate.translate( 'South Carolina' ) },
					{ code: 'sd', name: Translate.translate( 'South Dakota' ) },
					{ code: 'tn', name: Translate.translate( 'Tennessee' ) },
					{ code: 'tx', name: Translate.translate( 'Texas' ) },
					{ code: 'ut', name: Translate.translate( 'Utah' ) },
					{ code: 'vt', name: Translate.translate( 'Vermont' ) },
					{ code: 'va', name: Translate.translate( 'Virginia' ) },
					{ code: 'wa', name: Translate.translate( 'Washington' ) },
					{ code: 'wv', name: Translate.translate( 'West Virginia' ) },
					{ code: 'wi', name: Translate.translate( 'Wisconsin' ) },
					{ code: 'wy', name: Translate.translate( 'Wyoming' ) },
					{ code: 'dc', name: Translate.translate( 'Washington D.C.' ) },
					{ code: 'as', name: Translate.translate( 'American Samoa' ) },
					{ code: 'gu', name: Translate.translate( 'Guam' ) },
					{ code: 'mp', name: Translate.translate( 'Northern Mariana Islands' ) },
					{ code: 'pr', name: Translate.translate( 'Puerto Rico' ) },
					{ code: 'vi', name: Translate.translate( 'U.S. Virgin Islands' ) },
				];
			}
			else if ( country === 'ca' ) {
				this.regions[ country ] = [
					{ code: 'on', name: 'Ontario' },
					{ code: 'qc', name: 'Quebec' },
					{ code: 'ns', name: 'Nova Scotia' },
					{ code: 'nb', name: 'New Brunswick' },
					{ code: 'mb', name: 'Manitoba' },
					{ code: 'bc', name: 'British Columbia' },
					{ code: 'pe', name: 'Prince Edward Island' },
					{ code: 'sk', name: 'Saskatchewan' },
					{ code: 'ab', name: 'Alberta' },
					{ code: 'nl', name: 'Newfoundland and Labrador' },
					{ code: 'nt', name: 'Northwest Territories' },
					{ code: 'yt', name: 'Yukon' },
					{ code: 'nu', name: 'Nunavut' },
				];
			}
		}

		return this.regions[ country ];
	}
}
